# Creating NumPy Arrays 

There are multiple ways to create numpy arrays, the most commmon ones being:
* Convert lists or tuples to arrays using ```np.array()```
* Initialise arrays of fixed size (when the size is known) 

The following ways are commonly used:
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [1]:
# importing the NumPy library

import numpy as np

In [34]:
# creating an array with 4 elements and increments of a fixed step size
# default step size is one
np_1 = np.arange(1,6)


# creating an array of zeroes with 5 elements
np_2 = np.zeros(5)

In [14]:
# checking the created array: np_1
print(np_1)

[1 2 3 4 5]


In [35]:
# checking the created array:np_2
print(np_2)

[0. 0. 0. 0. 0.]


In [17]:
# data type of np_2
np_2.dtype

dtype('float64')

In [38]:
# specifying the data type of the array in the provided attribute

np.zeros(5,dtype="int")

array([0, 0, 0, 0, 0])

In [39]:
# adding the two arrays: np_1 and np_2
print(np_1 + np_2)

[1. 2. 3. 4. 5.]


In [27]:
# check the dimension of the arrays
# array np_1
np_1.size

5

In [28]:
# check the dimension of the arrays
# array np_2
np_2.size


6

In [30]:
# creating a third array with all the 5 elements as ones

np_3 = np.ones(5,dtype='int')

# checking the created array:np_3
print(np_3)

[1 1 1 1 1]


In [32]:
# check the dimension of the arrays
# array np_2
np_3.size


5

In [33]:
# subtracting the array np_3 from array np_2

print(np_2 - np_3)

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [41]:
# creating an array of fixed length
np_4 = np.linspace(1,10,5)

# checking the created array:np_4
print(np_4)

[ 1.    3.25  5.5   7.75 10.  ]


In [42]:
# checking the created array:np_1
np_1

array([1, 2, 3, 4, 5])

In [43]:
# squaring the terms of np_1
np.power(np_1,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [44]:
# getting the absolute value of the elements
np.absolute([-1,0,1,2,3])


array([1, 0, 1, 2, 3])

In [ ]:
# np.sin()
# np.cos()

In [ ]:
# np.log()

### Empty arrays

In [53]:
# Creating empty arrays

x = np.arange(1, 6)
y = np.empty(5,dtype='int')

# filling the empty array
np.multiply(x,5,out=y)


array([ 5, 10, 15, 20, 25])

In [54]:
# printing the output obtained above
y

array([ 5, 10, 15, 20, 25])

### Aggregation of array elements

In [55]:
# Reducing the elements to a single value based on addition
np.add.reduce(y)

75

In [56]:
# Cummulative addition of elements at each element
np.add.accumulate(y)

array([ 5, 15, 30, 50, 75], dtype=int32)

In [ ]:
np.linalg

In [57]:
help(np.linalg)

f a
                             Hermitian matrix.
        
        Notes
        -----
        The pseudo-inverse of a matrix A, denoted :math:`A^+`, is
        defined as: "the matrix that 'solves' [the least-squares problem]
        :math:`Ax = b`," i.e., if :math:`\bar{x}` is said solution, then
        :math:`A^+` is that matrix such that :math:`\bar{x} = A^+b`.
        
        It can be shown that if :math:`Q_1 \Sigma Q_2^T = A` is the singular
        value decomposition of A, then
        :math:`A^+ = Q_2 \Sigma^+ Q_1^T`, where :math:`Q_{1,2}` are
        orthogonal matrices, :math:`\Sigma` is a diagonal matrix consisting
        of A's so-called singular values, (followed, typically, by
        zeros), and then :math:`\Sigma^+` is simply the diagonal matrix
        consisting of the reciprocals of A's singular values
        (again, followed by zeros). [1]_
        
        References
        ----------
        .. [1] G. Strang, *Linear Algebra and Its Applications*, 2nd Ed.,

## Additional functions to initialize arrays in NumPy

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
* ```np.random.random()```: Create array of random numbers between 0 and 1
-  `np.random.randint()`: Create a random array of integers within a particular range

In [58]:
# Creating a 4 x 3 array of 7s using np.full()
# The default data type here is int only
np.full((4,3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [59]:
# Given an array, np.tile() creates a new array by repeating the given array for any number of times that you want
# The default data type her is int only
arr = ([0, 1, 2])
np.tile(arr, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [60]:
# You can also create multidimensional arrays using np.tile()
np.tile(arr, (3,2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [61]:
# Create a 3 x 3 identity matrix using np.eye()
# The default data type here is float. So if we want integer values, we need to specify the dtype to be int
np.eye(3, dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [62]:
# Create a 3 x 3 array of random numbers between 0 and 1
np.random.random([3, 4])

array([[0.10038858, 0.06811254, 0.87155385, 0.98918944],
       [0.40054628, 0.93735271, 0.97760652, 0.28959842],
       [0.73730127, 0.97582494, 0.85850086, 0.62316985]])

In [64]:
# Create a 4 x 4 random array of integers ranging from 0 to 9
np.random.randint(0, 10, (4,4))

array([[8, 7, 9, 1],
       [2, 3, 9, 7],
       [8, 6, 4, 2],
       [7, 9, 4, 9]])